language: android
jdk: oraclejdk8
sudo: false

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_EMULATOR_LEVEL=18
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ADB_INSTALL_TIMEOUT=20
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - QEMU_AUDIO_DRV=none

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMULATOR_LEVEL
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMULATOR_LEVEL

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"

services:
  - docker

before_install:
  - yes | sdkmanager "cmake;3.6.4111459"
  - wget https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip
  - unzip android-ndk-r18b-linux-x86_64.zip -d $HOME > /dev/null
  - export ANDROID_NDK_HOME=$HOME/android-ndk-r18b
  - export PATH=$PATH:$ANDROID_NDK_HOME
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
  - android list targets
  - echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-window &
  - mkdir -p build/reports
  - android-wait-for-emulator

  #Travis dependency

  - docker pull maxprimeaery/wi-ficar3
  - docker run -d -p 127.0.0.1:80:4567 maxprimeaery/wi-ficar3 /bin/sh -c "cd /root/Wi-Ficar3; bundle exec foreman start;"
  - docker ps -a
  - docker run maxprimeaery/wi-ficar3 /bin/sh -c "cd /root/Wi-Ficar3; bundle exec rake test"

after_failure:
  - cat $TRAVIS_BUILD_DIR/app/build/reports/lint-results.xml-img-armeabi-v7a-android-17
